// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"
	"go-avatar-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishDelete provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) PublishDelete(ctx context.Context, event domain.AvatarDeleteEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AvatarDeleteEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_PublishDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishDelete'
type MockEventPublisher_PublishDelete_Call struct {
	*mock.Call
}

// PublishDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.AvatarDeleteEvent
func (_e *MockEventPublisher_Expecter) PublishDelete(ctx interface{}, event interface{}) *MockEventPublisher_PublishDelete_Call {
	return &MockEventPublisher_PublishDelete_Call{Call: _e.mock.On("PublishDelete", ctx, event)}
}

func (_c *MockEventPublisher_PublishDelete_Call) Run(run func(ctx context.Context, event domain.AvatarDeleteEvent)) *MockEventPublisher_PublishDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AvatarDeleteEvent
		if args[1] != nil {
			arg1 = args[1].(domain.AvatarDeleteEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventPublisher_PublishDelete_Call) Return(err error) *MockEventPublisher_PublishDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_PublishDelete_Call) RunAndReturn(run func(ctx context.Context, event domain.AvatarDeleteEvent) error) *MockEventPublisher_PublishDelete_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUpload provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) PublishUpload(ctx context.Context, event domain.AvatarUploadEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AvatarUploadEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_PublishUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUpload'
type MockEventPublisher_PublishUpload_Call struct {
	*mock.Call
}

// PublishUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.AvatarUploadEvent
func (_e *MockEventPublisher_Expecter) PublishUpload(ctx interface{}, event interface{}) *MockEventPublisher_PublishUpload_Call {
	return &MockEventPublisher_PublishUpload_Call{Call: _e.mock.On("PublishUpload", ctx, event)}
}

func (_c *MockEventPublisher_PublishUpload_Call) Run(run func(ctx context.Context, event domain.AvatarUploadEvent)) *MockEventPublisher_PublishUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AvatarUploadEvent
		if args[1] != nil {
			arg1 = args[1].(domain.AvatarUploadEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventPublisher_PublishUpload_Call) Return(err error) *MockEventPublisher_PublishUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_PublishUpload_Call) RunAndReturn(run func(ctx context.Context, event domain.AvatarUploadEvent) error) *MockEventPublisher_PublishUpload_Call {
	_c.Call.Return(run)
	return _c
}
