// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package worker

import (
	"context"
	"go-avatar-service/internal/domain"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Avatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Avatar, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Avatar); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(avatar *domain.Avatar, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(avatar, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Avatar, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPendingOlderThan provides a mock function for the type MockRepository
func (_mock *MockRepository) ListPendingOlderThan(ctx context.Context, age time.Duration, limit int) ([]domain.Avatar, error) {
	ret := _mock.Called(ctx, age, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingOlderThan")
	}

	var r0 []domain.Avatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) ([]domain.Avatar, error)); ok {
		return returnFunc(ctx, age, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) []domain.Avatar); ok {
		r0 = returnFunc(ctx, age, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Avatar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = returnFunc(ctx, age, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListPendingOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPendingOlderThan'
type MockRepository_ListPendingOlderThan_Call struct {
	*mock.Call
}

// ListPendingOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - age time.Duration
//   - limit int
func (_e *MockRepository_Expecter) ListPendingOlderThan(ctx interface{}, age interface{}, limit interface{}) *MockRepository_ListPendingOlderThan_Call {
	return &MockRepository_ListPendingOlderThan_Call{Call: _e.mock.On("ListPendingOlderThan", ctx, age, limit)}
}

func (_c *MockRepository_ListPendingOlderThan_Call) Run(run func(ctx context.Context, age time.Duration, limit int)) *MockRepository_ListPendingOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_ListPendingOlderThan_Call) Return(avatars []domain.Avatar, err error) *MockRepository_ListPendingOlderThan_Call {
	_c.Call.Return(avatars, err)
	return _c
}

func (_c *MockRepository_ListPendingOlderThan_Call) RunAndReturn(run func(ctx context.Context, age time.Duration, limit int) ([]domain.Avatar, error)) *MockRepository_ListPendingOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// SetProcessingStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) SetProcessingStatus(ctx context.Context, id uuid.UUID, status domain.ProcessingStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for SetProcessingStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ProcessingStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetProcessingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetProcessingStatus'
type MockRepository_SetProcessingStatus_Call struct {
	*mock.Call
}

// SetProcessingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status domain.ProcessingStatus
func (_e *MockRepository_Expecter) SetProcessingStatus(ctx interface{}, id interface{}, status interface{}) *MockRepository_SetProcessingStatus_Call {
	return &MockRepository_SetProcessingStatus_Call{Call: _e.mock.On("SetProcessingStatus", ctx, id, status)}
}

func (_c *MockRepository_SetProcessingStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status domain.ProcessingStatus)) *MockRepository_SetProcessingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.ProcessingStatus
		if args[2] != nil {
			arg2 = args[2].(domain.ProcessingStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetProcessingStatus_Call) Return(err error) *MockRepository_SetProcessingStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetProcessingStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status domain.ProcessingStatus) error) *MockRepository_SetProcessingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcessingResult provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateProcessingResult(ctx context.Context, id uuid.UUID, thumbnails map[string]string, width int, height int) (bool, error) {
	ret := _mock.Called(ctx, id, thumbnails, width, height)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcessingResult")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]string, int, int) (bool, error)); ok {
		return returnFunc(ctx, id, thumbnails, width, height)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]string, int, int) bool); ok {
		r0 = returnFunc(ctx, id, thumbnails, width, height)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]string, int, int) error); ok {
		r1 = returnFunc(ctx, id, thumbnails, width, height)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_UpdateProcessingResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcessingResult'
type MockRepository_UpdateProcessingResult_Call struct {
	*mock.Call
}

// UpdateProcessingResult is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - thumbnails map[string]string
//   - width int
//   - height int
func (_e *MockRepository_Expecter) UpdateProcessingResult(ctx interface{}, id interface{}, thumbnails interface{}, width interface{}, height interface{}) *MockRepository_UpdateProcessingResult_Call {
	return &MockRepository_UpdateProcessingResult_Call{Call: _e.mock.On("UpdateProcessingResult", ctx, id, thumbnails, width, height)}
}

func (_c *MockRepository_UpdateProcessingResult_Call) Run(run func(ctx context.Context, id uuid.UUID, thumbnails map[string]string, width int, height int)) *MockRepository_UpdateProcessingResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]string
		if args[2] != nil {
			arg2 = args[2].(map[string]string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateProcessingResult_Call) Return(b bool, err error) *MockRepository_UpdateProcessingResult_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_UpdateProcessingResult_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, thumbnails map[string]string, width int, height int) (bool, error)) *MockRepository_UpdateProcessingResult_Call {
	_c.Call.Return(run)
	return _c
}
