// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services_test

import (
	"context"
	"go-avatar-service/internal/domain"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockObjectStorage creates a new instance of MockObjectStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStorage {
	mock := &MockObjectStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStorage is an autogenerated mock type for the ObjectStorage type
type MockObjectStorage struct {
	mock.Mock
}

type MockObjectStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStorage) EXPECT() *MockObjectStorage_Expecter {
	return &MockObjectStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockObjectStorage
func (_mock *MockObjectStorage) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockObjectStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStorage_Expecter) Delete(ctx interface{}, key interface{}) *MockObjectStorage_Delete_Call {
	return &MockObjectStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockObjectStorage_Delete_Call) Run(run func(ctx context.Context, key string)) *MockObjectStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStorage_Delete_Call) Return(err error) *MockObjectStorage_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStorage_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockObjectStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type MockObjectStorage
func (_mock *MockObjectStorage) DeleteMany(ctx context.Context, keys []string) error {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStorage_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockObjectStorage_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockObjectStorage_Expecter) DeleteMany(ctx interface{}, keys interface{}) *MockObjectStorage_DeleteMany_Call {
	return &MockObjectStorage_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, keys)}
}

func (_c *MockObjectStorage_DeleteMany_Call) Run(run func(ctx context.Context, keys []string)) *MockObjectStorage_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStorage_DeleteMany_Call) Return(err error) *MockObjectStorage_DeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStorage_DeleteMany_Call) RunAndReturn(run func(ctx context.Context, keys []string) error) *MockObjectStorage_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockObjectStorage
func (_mock *MockObjectStorage) Get(ctx context.Context, key string) (*domain.Object, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Object, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Object); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockObjectStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStorage_Expecter) Get(ctx interface{}, key interface{}) *MockObjectStorage_Get_Call {
	return &MockObjectStorage_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockObjectStorage_Get_Call) Run(run func(ctx context.Context, key string)) *MockObjectStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStorage_Get_Call) Return(object *domain.Object, err error) *MockObjectStorage_Get_Call {
	_c.Call.Return(object, err)
	return _c
}

func (_c *MockObjectStorage_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (*domain.Object, error)) *MockObjectStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockObjectStorage
func (_mock *MockObjectStorage) Put(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	ret := _mock.Called(ctx, key, r, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = returnFunc(ctx, key, r, size, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStorage_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockObjectStorage_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - r io.Reader
//   - size int64
//   - contentType string
func (_e *MockObjectStorage_Expecter) Put(ctx interface{}, key interface{}, r interface{}, size interface{}, contentType interface{}) *MockObjectStorage_Put_Call {
	return &MockObjectStorage_Put_Call{Call: _e.mock.On("Put", ctx, key, r, size, contentType)}
}

func (_c *MockObjectStorage_Put_Call) Run(run func(ctx context.Context, key string, r io.Reader, size int64, contentType string)) *MockObjectStorage_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockObjectStorage_Put_Call) Return(err error) *MockObjectStorage_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStorage_Put_Call) RunAndReturn(run func(ctx context.Context, key string, r io.Reader, size int64, contentType string) error) *MockObjectStorage_Put_Call {
	_c.Call.Return(run)
	return _c
}
