// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services_test

import (
	"context"
	"go-avatar-service/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAvatarRepository creates a new instance of MockAvatarRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAvatarRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAvatarRepository {
	mock := &MockAvatarRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAvatarRepository is an autogenerated mock type for the AvatarRepository type
type MockAvatarRepository struct {
	mock.Mock
}

type MockAvatarRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAvatarRepository) EXPECT() *MockAvatarRepository_Expecter {
	return &MockAvatarRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) Create(ctx context.Context, a *domain.Avatar) error {
	ret := _mock.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Avatar) error); ok {
		r0 = returnFunc(ctx, a)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAvatarRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAvatarRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *domain.Avatar
func (_e *MockAvatarRepository_Expecter) Create(ctx interface{}, a interface{}) *MockAvatarRepository_Create_Call {
	return &MockAvatarRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockAvatarRepository_Create_Call) Run(run func(ctx context.Context, a *domain.Avatar)) *MockAvatarRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Avatar
		if args[1] != nil {
			arg1 = args[1].(*domain.Avatar)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_Create_Call) Return(err error) *MockAvatarRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAvatarRepository_Create_Call) RunAndReturn(run func(ctx context.Context, a *domain.Avatar) error) *MockAvatarRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Avatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Avatar, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Avatar); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAvatarRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAvatarRepository_GetByID_Call {
	return &MockAvatarRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAvatarRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_GetByID_Call) Return(avatar *domain.Avatar, err error) *MockAvatarRepository_GetByID_Call {
	_c.Call.Return(avatar, err)
	return _c
}

func (_c *MockAvatarRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Avatar, error)) *MockAvatarRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentByUserID provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) GetCurrentByUserID(ctx context.Context, userID string) (*domain.Avatar, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentByUserID")
	}

	var r0 *domain.Avatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Avatar, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Avatar); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_GetCurrentByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentByUserID'
type MockAvatarRepository_GetCurrentByUserID_Call struct {
	*mock.Call
}

// GetCurrentByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAvatarRepository_Expecter) GetCurrentByUserID(ctx interface{}, userID interface{}) *MockAvatarRepository_GetCurrentByUserID_Call {
	return &MockAvatarRepository_GetCurrentByUserID_Call{Call: _e.mock.On("GetCurrentByUserID", ctx, userID)}
}

func (_c *MockAvatarRepository_GetCurrentByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAvatarRepository_GetCurrentByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_GetCurrentByUserID_Call) Return(avatar *domain.Avatar, err error) *MockAvatarRepository_GetCurrentByUserID_Call {
	_c.Call.Return(avatar, err)
	return _c
}

func (_c *MockAvatarRepository_GetCurrentByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.Avatar, error)) *MockAvatarRepository_GetCurrentByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) ListByUserID(ctx context.Context, userID string) ([]domain.Avatar, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []domain.Avatar
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Avatar, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Avatar); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Avatar)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockAvatarRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAvatarRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockAvatarRepository_ListByUserID_Call {
	return &MockAvatarRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockAvatarRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAvatarRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_ListByUserID_Call) Return(avatars []domain.Avatar, err error) *MockAvatarRepository_ListByUserID_Call {
	_c.Call.Return(avatars, err)
	return _c
}

func (_c *MockAvatarRepository_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]domain.Avatar, error)) *MockAvatarRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockAvatarRepository
func (_mock *MockAvatarRepository) SoftDelete(ctx context.Context, id uuid.UUID, userID string) ([]string, error) {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]string, error)); ok {
		return returnFunc(ctx, id, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []string); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAvatarRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockAvatarRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID string
func (_e *MockAvatarRepository_Expecter) SoftDelete(ctx interface{}, id interface{}, userID interface{}) *MockAvatarRepository_SoftDelete_Call {
	return &MockAvatarRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id, userID)}
}

func (_c *MockAvatarRepository_SoftDelete_Call) Run(run func(ctx context.Context, id uuid.UUID, userID string)) *MockAvatarRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAvatarRepository_SoftDelete_Call) Return(strings []string, err error) *MockAvatarRepository_SoftDelete_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockAvatarRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID string) ([]string, error)) *MockAvatarRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishDelete provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) PublishDelete(ctx context.Context, event domain.AvatarDeleteEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AvatarDeleteEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_PublishDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishDelete'
type MockEventPublisher_PublishDelete_Call struct {
	*mock.Call
}

// PublishDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.AvatarDeleteEvent
func (_e *MockEventPublisher_Expecter) PublishDelete(ctx interface{}, event interface{}) *MockEventPublisher_PublishDelete_Call {
	return &MockEventPublisher_PublishDelete_Call{Call: _e.mock.On("PublishDelete", ctx, event)}
}

func (_c *MockEventPublisher_PublishDelete_Call) Run(run func(ctx context.Context, event domain.AvatarDeleteEvent)) *MockEventPublisher_PublishDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AvatarDeleteEvent
		if args[1] != nil {
			arg1 = args[1].(domain.AvatarDeleteEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventPublisher_PublishDelete_Call) Return(err error) *MockEventPublisher_PublishDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_PublishDelete_Call) RunAndReturn(run func(ctx context.Context, event domain.AvatarDeleteEvent) error) *MockEventPublisher_PublishDelete_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUpload provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) PublishUpload(ctx context.Context, event domain.AvatarUploadEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AvatarUploadEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_PublishUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUpload'
type MockEventPublisher_PublishUpload_Call struct {
	*mock.Call
}

// PublishUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.AvatarUploadEvent
func (_e *MockEventPublisher_Expecter) PublishUpload(ctx interface{}, event interface{}) *MockEventPublisher_PublishUpload_Call {
	return &MockEventPublisher_PublishUpload_Call{Call: _e.mock.On("PublishUpload", ctx, event)}
}

func (_c *MockEventPublisher_PublishUpload_Call) Run(run func(ctx context.Context, event domain.AvatarUploadEvent)) *MockEventPublisher_PublishUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AvatarUploadEvent
		if args[1] != nil {
			arg1 = args[1].(domain.AvatarUploadEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventPublisher_PublishUpload_Call) Return(err error) *MockEventPublisher_PublishUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_PublishUpload_Call) RunAndReturn(run func(ctx context.Context, event domain.AvatarUploadEvent) error) *MockEventPublisher_PublishUpload_Call {
	_c.Call.Return(run)
	return _c
}
